spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher

keys:
  apiKey: b9d5c427

extern:
  imdb:
    baseUrl: https://www.omdbapi.com/?apikey=b9d5c427
