spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop

keys:
  apiKey: k_pcv4eo6i

extern:
  imdb:
    baseUrl: https://imdb-api.com/API
    movies:
      top250:
        url: /Top250Movies/${keys.apiKey}
      title:
        url: /Title/${keys.apiKey}/{id}
