version: '3'

services:
  zookeeper:
    container_name: zookeeper_local
    restart: always
    image: 'bitnami/zookeeper:latest'
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_volume:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    container_name: kafka_local
    image: 'bitnami/kafka:latest'
    restart: always
    ports:
      - "9093:9093"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://localhost:9093
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
    depends_on:
      - zookeeper

  kafka-ui:
    container_name: kafka_ui_local
    image: 'provectuslabs/kafka-ui:latest'
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      DYNAMIC_CONFIG_ENABLED: 'false'
    ports:
      - 9090:8080
    depends_on:
      - kafka
volumes:
  zookeeper_volume:
    driver: local
  kafka_volume:
    driver: local